import 'package:flutter/material.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
void main()=>runApp(const MaterialApp(home:AymaPage(),debugShowCheckedModeBanner:false));
class Item{String n,c;double p;int q;Item(this.n,this.c,this.p,this.q);Map toJson()=>{'n':n,'c':c,'p':p,'q':q};static fromJson(m)=>Item(m['n'],m['c'],(m['p']as num).toDouble(),m['q']);}
class AymaPage extends StatefulWidget{const AymaPage({super.key});@override State<AymaPage> createState()=>_S();}
class _S extends State<AymaPage>{
TextEditingController bride=TextEditingController(),groom=TextEditingController(),gold=TextEditingController(text:'0'),moakhar=TextEditingController(text:'0'),nameC=TextEditingController(),priceC=TextEditingController(),qtyC=TextEditingController(text:'1');
List<Item> items=[];String filter='الكل';List<String> cats=['الكل','أوضة النوم','المطبخ','النيش','الأجهزة','الدهب','المفروشات','أخرى'];String selCat='أوضة النوم';
@override void initState(){super.initState();SharedPreferences.getInstance().then((p){setState((){bride.text=p.getString('bride')??'';groom.text=p.getString('groom')??'';gold.text=p.getString('gold')??'0';moakhar.text=p.getString('moakhar')??'0';var s=p.getString('items');if(s!=null)items=(jsonDecode(s)as List).map((e)=>Item.fromJson(e)).toList();});});}
save() async{var p=await SharedPreferences.getInstance();p.setString('bride',bride.text);p.setString('groom',groom.text);p.setString('gold',gold.text);p.setString('moakhar',moakhar.text);p.setString('items',jsonEncode(items.map((e)=>e.toJson()).toList()));}
double get total=>items.fold(0,(a,b)=>a+b.p*b.q)+(double.tryParse(gold.text)??0)+(double.tryParse(moakhar.text)??0);
makePdf() async{var doc=pw.Document();doc.addPage(pw.Page(build:(c)=>pw.Column(children:[pw.Text('قائمة منقولات زوجية'),pw.Text('العريس: ${groom.text} - العروسة: ${bride.text}'),pw.Table.fromTextArray(headers:['الصنف','العدد','السعر'],data:[for(var it in items)[it.n,'${it.q}','${it.p}']]),pw.Text('الإجمالي: $total')])));await Printing.sharePdf(bytes:await doc.save(),filename:'qayma.pdf');}
@override Widget build(BuildContext context){var f=filter=='الكل'?items:items.where((e)=>e.c==filter).toList();return Scaffold(appBar:AppBar(title:const Text('القايمة'),backgroundColor:const Color(0xFF8B5A2B),foregroundColor:Colors.white,actions:[IconButton(onPressed:makePdf,icon:const Icon(Icons.picture_as_pdf))]),floatingActionButton:FloatingActionButton(onPressed:(){showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('إضافة'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:nameC,decoration:const InputDecoration(labelText:'الاسم')),TextField(controller:priceC,decoration:const InputDecoration(labelText:'السعر'),keyboardType:TextInputType.number),TextField(controller:qtyC,decoration:const InputDecoration(labelText:'العدد'),keyboardType:TextInputType.number)]),actions:[ElevatedButton(onPressed:(){if(nameC.text.isEmpty)return;setState(()=>items.add(Item(nameC.text,selCat,double.tryParse(priceC.text)??0,int.tryParse(qtyC.text)??1)));nameC.clear();priceC.clear();save();Navigator.pop(context);},child:const Text('إضافة'))]));},child:const Icon(Icons.add)),body:ListView(padding:const EdgeInsets.all(10),children:[Row(children:[Expanded(child:TextField(controller:groom,decoration:const InputDecoration(labelText:'العريس',border:OutlineInputBorder()))),const SizedBox(width:6),Expanded(child:TextField(controller:bride,decoration:const InputDecoration(labelText:'العروسة',border:OutlineInputBorder())))]),const SizedBox(height:6),Row(children:[Expanded(child:TextField(controller:gold,decoration:const InputDecoration(labelText:'الدهب',border:OutlineInputBorder()),keyboardType:TextInputType.number)),const SizedBox(width:6),Expanded(child:TextField(controller:moakhar,decoration:const InputDecoration(labelText:'المؤخر',border:OutlineInputBorder()),keyboardType:TextInputType.number))]),SizedBox(height:35,child:ListView(scrollDirection:Axis.horizontal,children:cats.map((c)=>Padding(padding:const EdgeInsets.only(right:5),child:ChoiceChip(label:Text(c),selected:filter==c,onSelected:(_)=>setState(()=>filter=c)))).toList())),Text('الإجمالي: $total ج',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:18)),...f.map((e)=>Card(child:ListTile(title:Text(e.n),subtitle:Text('${e.c} ${e.p}'),trailing:IconButton(icon:const Icon(Icons.delete,color:Colors.red),onPressed:(){setState(()=>items.remove(e));save();}))))]));}
}
