name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
      - name: Fix gradle project
        run: |
          ls -la
          cp pubspec.yaml /tmp/pubspec.yaml
          cp lib/main.dart /tmp/main.dart
          flutter create . --project-name elayma --org com.elayma.app
          cp /tmp/pubspec.yaml pubspec.yaml
          cp /tmp/main.dart lib/main.dart
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: elayma-apk
          path: build/app/outputs/flutter-apk/app-release.apk
